#!/usr/bin/env python

import matplotlib.pyplot as plt
import sys
from scipy import signal
import numpy as np
import glob
import os
import math
import argparse


from px4tuning import sysid
from px4tuning import vrft
from px4tuning import importa






parser = argparse.ArgumentParser()
parser.add_argument('--plot', action='store_true', help="enable plotting")
parser.add_argument('file', nargs='?', help='file.ulg')

args = parser.parse_args()

if args.file:
    arq=args.file
else:
    list_of_files=glob.glob('*.ulg')
    arq = max(list_of_files, key=os.path.getctime)
print("Arquivo", arq)

arq='log_2_2018-10-8-14-18-26.ulg'
arq='log_4_2018-10-9-12-11-06.ulg'

D=importa.open_file(arq)

if 1:

    K=180/math.pi
    t0=D.t0*1e-6
    
    
    p1=plt.figure(1)
    plt.plot(t0,D.u_r, label='roll')
    plt.plot(t0,D.u_p, label='pitch')
    plt.plot(t0,D.u_y, label='yaw')
    plt.plot(t0,D.u_z, label='z')
    plt.ylabel('u')
    plt.legend()

    
